### ISSUE TITLE
[BUG]: sonic_lag_interfaces module fails to set the port-channel ID on interfaces

### ISSUE THREAD

**Issue by matthew-hannon-dell** [ansible-collections/dellemc.enterprise_sonic#153]
### Bug Description

The sonic_lag_interfaces module fails to set the port-channel ID on interfaces due to sending an incorrect string in the body. For example, if we want to assign PortChannel55 to Eth1/11 the string that should be sent is "openconfig-if-aggregate:aggregate-id": "PortChannel55" however the module appears to be sending just "openconfig-if-aggregate:aggregate-id": "55"

### Product Name

Dell Enterprise SONiC

### Component or Module Name

sonic_lag_interfaces

### DellEMC Enterprise SONiC Ansible Collection Version

dellemc.enterprise_sonic 2.0.0

### SONiC Software Version

Software Version  : '4.0.2-Enterprise_Base'

### Configuration

admin@AnsibleDeploymentStation:~$ ansible-config dump --only-changed
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the
controller starting with Ansible 2.12. Current version: 3.7.3 (default, Oct 31
2022, 14:04:00) [GCC 8.3.0]. This feature will be removed from ansible-core in
version 2.12. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
admin@AnsibleDeploymentStation:~$

### Steps to Reproduce

To reproduce attempt to leverage the sonic_lag_interfaces module with SONiC 4.0.2 to set a port-channel. Example config passed to the module: 

  - members:
      interfaces:
        - member: Eth1/11
        - member: Eth1/12
    mode: lacp
    name: PortChannel55

### Expected Behavior

I would expect the module to set the port-channel ID on the member ports

### Actual Behavior

TASK [Create LAG Interfaces] ***************************************************
fatal: [dcn01-s5212-01-sonic]: FAILED! => {"changed": false, "code": -32603, "msg": "{'ietf-restconf:errors': {'error': [{'error-type': 'application', 'error-tag': 'invalid-value', 'error-message': 'Invalid Interface:55'}]}, 'code': 400, 'request_data': {'path': 'data/openconfig-interfaces:interfaces/interface=Eth1%2F11/openconfig-if-ethernet:ethernet/config/openconfig-if-aggregate:aggregate-id', 'method': 'patch'}}"}

### Logs

TASK [Create LAG Interfaces] ***************************************************
fatal: [dcn01-s5212-01-sonic]: FAILED! => {"changed": false, "code": -32603, "msg": "{'ietf-restconf:errors': {'error': [{'error-type': 'application', 'error-tag': 'invalid-value', 'error-message': 'Invalid Interface:55'}]}, 'code': 400, 'request_data': {'path': 'data/openconfig-interfaces:interfaces/interface=Eth1%2F11/openconfig-if-ethernet:ethernet/config/openconfig-if-aggregate:aggregate-id', 'method': 'patch'}}"}

**Comment by fabrifagundes** [comment]
I have the same issue here :(

**Comment by kerry-meyer** [comment]
A fix for this problem was merged to the "main" branch of our repo with the following PR: "https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/119" (Deleted port name split for lag_interfaces). It will be included in the upcoming 2.1.0 release of the Dell Enterprise SONiC Ansible resource module collection.
