### ISSUE TITLE
[BUG]: sonic_l2_interfaces module errors when multiple allowed VLANs are in sequential order

### ISSUE THREAD

**Issue by matthew-hannon-dell** [ansible-collections/dellemc.enterprise_sonic#154]
### Bug Description

When the sonic_l2_interfaces module is run with consecutive vlans it properly sets the range but then errors out with a message of "fatal: [dcn01-s5212-01-sonic]: FAILED! => {"changed": false, "msg": "argument 'vlan' is of type <class 'str'> found in 'config -> trunk -> allowed_vlans'. and we were unable to convert to int: <class 'str'> cannot be converted to an int"}".  This appears to be the result of the return value being a string that describes the range.

### Product Name

Dell Enterprise SONiC

### Component or Module Name

sonic_l2_interfaces

### DellEMC Enterprise SONiC Ansible Collection Version

dellemc.enterprise_sonic 2.0.0

### SONiC Software Version

Software Version  : '4.0.2-Enterprise_Base'

### Configuration

admin@AnsibleDeploymentStation:~/test$ ansible-config dump --only-changed
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the
controller starting with Ansible 2.12. Current version: 3.7.3 (default, Oct 31
2022, 14:04:00) [GCC 8.3.0]. This feature will be removed from ansible-core in
version 2.12. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
admin@AnsibleDeploymentStation:~/test$

### Steps to Reproduce

Run the sonic_l2_interfaces module against SONiC 4.0.2 with a config of 
  - name: PortChannel255
    access:
      vlan: 1
    trunk:
      allowed_vlans:
        - vlan: 2
        - vlan: 3

### Expected Behavior

The vlans would be set and no error would occur.

### Actual Behavior

When the sonic_l2_interfaces module is run with consecutive vlans it properly sets the range but then errors out with a message of "fatal: [dcn01-s5212-01-sonic]: FAILED! => {"changed": false, "msg": "argument 'vlan' is of type <class 'str'> found in 'config -> trunk -> allowed_vlans'. and we were unable to convert to int: <class 'str'> cannot be converted to an int"}". 

### Logs

------------------------------------------------------------------------------------------------------------------
config file definition for sonic_l2_interfaces:
------------------------------------------------------------------------------------------------------------------
  - name: PortChannel255
    access:
      vlan: 1
    trunk:
      allowed_vlans:
        - vlan: 2
        - vlan: 3

------------------------------------------------------------------------------------------------------------------
Result
------------------------------------------------------------------------------------------------------------------
TASK [Configure L2 Interfaces] *************************************************
task path: /home/admin/test/playbook.yml:67
redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
redirecting (type: action) dellemc.enterprise_sonic.sonic_l2_interfaces to dellemc.enterprise_sonic.sonic
redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
redirecting (type: action) dellemc.enterprise_sonic.sonic_l2_interfaces to dellemc.enterprise_sonic.sonic
redirecting (type: action) dellemc.enterprise_sonic.sonic_l2_interfaces to dellemc.enterprise_sonic.sonic
redirecting (type: action) dellemc.enterprise_sonic.sonic_l2_interfaces to dellemc.enterprise_sonic.sonic
redirecting (type: action) dellemc.enterprise_sonic.sonic_l2_interfaces to dellemc.enterprise_sonic.sonic
fatal: [dcn01-s5212-01-sonic]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "config": [
                {
                    "access": {
                        "vlan": 2
                    },
                    "name": "Eth1/1",
                    "trunk": {
                        "allowed_vlans": [
                            {
                                "vlan": 3
                            }
                        ]
                    }
                },
                {
                    "access": {
                        "vlan": 1
                    },
                    "name": "Eth1/10",
                    "trunk": null
                },
                {
                    "access": {
                        "vlan": 1
                    },
                    "name": "Eth1/15",
                    "trunk": null
                },
                {
                    "access": {
                        "vlan": 2
                    },
                    "name": "Eth1/2",
                    "trunk": {
                        "allowed_vlans": [
                            {
                                "vlan": 3
                            }
                        ]
                    }
                },
                {
                    "access": {
                        "vlan": 1
                    },
                    "name": "Eth1/3",
                    "trunk": null
                },
                {
                    "access": {
                        "vlan": 1
                    },
                    "name": "Eth1/4",
                    "trunk": null
                },
                {
                    "access": {
                        "vlan": 1
                    },
                    "name": "Eth1/5",
                    "trunk": null
                },
                {
                    "access": {
                        "vlan": 1
                    },
                    "name": "Eth1/6",
                    "trunk": null
                },
                {
                    "access": {
                        "vlan": 1
                    },
                    "name": "Eth1/7",
                    "trunk": null
                },
                {
                    "access": {
                        "vlan": 1
                    },
                    "name": "Eth1/8",
                    "trunk": null
                },
                {
                    "access": {
                        "vlan": 1
                    },
                    "name": "Eth1/9",
                    "trunk": null
                },
                {
                    "access": {
                        "vlan": 1
                    },
                    "name": "PortChannel255",
                    "trunk": {
                        "allowed_vlans": [
                            {
                                "vlan": "2..3"
                            }
                        ]
                    }
                }
            ],
            "state": "merged"
        }
    },
    "msg": "argument 'vlan' is of type <class 'str'> found in 'config -> trunk -> allowed_vlans'. and we were unable to convert to int: <class 'str'> cannot be converted to an int"
}

**Comment by kerry-meyer** [comment]
A fix for this problem was merged to the "main" branch of our repo with the following PR: "https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/149" (playbook support for vlan trunk ranges). It will be included in the upcoming 2.1.0 release of the Dell Enterprise SONiC Ansible resource module collection.
