### ISSUE TITLE
[FEATURE]: module for STP operations

### ISSUE THREAD

**Issue by matthew-hannon-dell** [ansible-collections/dellemc.enterprise_sonic#155]
Currently, there doesn't appear to be any module that addresses STP operations either globally or per interface. As a huge percentage of environments still leverage STP this would be a helpful addition. The most common STP configurations that we set on projects are:
* Setting STP mode globally (Rapid-PVST, PVST, MST, Disabled)
* Setting priority per VLAN for Rapid-PVST/PVST
* Setting priority per instance with MST
* Setting per port settings such
  * BPDUguard
  * Rootguard
  * Loopguard
  * Edge port / Portfast mode
  * STP Disabled per interface

**Comment by kerry-meyer** [comment]
This issue has been addressed by the merging of the following PR:

https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/286 (Added STP module)

**Comment by kerry-meyer** [comment]
This issue has been addressed by the merging of the following PR:

https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/286 (Added STP module)
