### ISSUE TITLE
[BUG]: deleting one IP address from interface is removing all IP addresses

### ISSUE THREAD

**Issue by kannankvs** [ansible-collections/dellemc.enterprise_sonic#170]
### Bug Description

Configure more than 1 IP addresses on an interface as follows (using CLI) and then try to remove one of the secondary addresses using the playbook. This deletes all IP addresses instead of deleting one of them.
conf t
interface-naming standard extended
interface Ethernet0
 ip address 11.22.33.44/8
 ip address 55.66.77.88/8 secondary
 ip address 1.1.1.1/8 secondary
 ip address 2.2.2.2/8 secondary

PLAYBOOK:
---
- name: Ansible resource module example
  hosts: datacenter
  gather_facts: False
  connection: httpapi
  collections:
    - dellemc.enterprise_sonic
  tasks:
    - name: sonic_l3_interfaces IP delete
      sonic_l3_interfaces:
        config:
        - name: Ethernet0
          ipv4:
            addresses:
              - address: 55.66.77.88/8
                secondary: True
        state: deleted

** POSSIBLE SOLUTION: ** 
File: plugins/module_utils/network/sonic/config/l3_interfaces/l3_interfaces.py
Definition: get_delete_l3_interfaces_requests
Buggy Line: elif ipv4 and ipv4.get('addresses') and not ipv4.get('anycast_addresses'):
Possible Solution: elif ipv4 and not ipv4.get('addresses') and not ipv4.get('anycast_addresses'):

### Product Name

eSONiC AnsibleCollections

### Component or Module Name

sonic_l3_interfaces

### DellEMC Enterprise SONiC Ansible Collection Version

All collections

### SONiC Software Version

all esonic versions

### Configuration

conf t
interface-naming standard extended
interface Ethernet0
 ip address 11.22.33.44/8
 ip address 55.66.77.88/8 secondary
 ip address 1.1.1.1/8 secondary
 ip address 2.2.2.2/8 secondary

### Steps to Reproduce

Run the playbook
PLAYBOOK:
---
- name: Ansible resource module example
  hosts: datacenter
  gather_facts: False
  connection: httpapi
  collections:
    - dellemc.enterprise_sonic
  tasks:
    - name: sonic_l3_interfaces IP delete
      sonic_l3_interfaces:
        config:
        - name: Ethernet0
          ipv4:
            addresses:
              - address: 55.66.77.88/8
                secondary: True
        state: deleted

### Expected Behavior

Supposed to remove only the "55.66.77.88/8" from the list of IP addresses.

### Actual Behavior

All IP addresses are getting deleted.

### Logs

ALL IP addresses are gone.

**Comment by kerry-meyer** [comment]
I am closing this bug because the fix has been merged.
