### ISSUE TITLE
[BUG]: argspec validation error seen while using ‘sonic_port_breakout’ module in Z9432F-ON platform.

### ISSUE THREAD

**Issue by Dhivyap** [ansible-collections/dellemc.enterprise_sonic#189]
### Bug Description

Z9432F platform supports 8x10G and 8x25G breakout modes when changing hardware SKU from default to ‘DellEMC-Z9432f-T64C64O8-DPB’.
But ‘sonic_port_breakout’ module throws the below error when the facts have any of the above breakout modes.

Ansible module error:
"value of mode must be one of: 1x100G, 1x400G, 1x40G, 2x100G, 2x200G, 2x50G, 4x100G, 4x10G, 4x25G, 4x50G, got: 8x25G found in config"

### Product Name

Dell Enterprise SONiC

### Component or Module Name

sonic_port_breakout

### DellEMC Enterprise SONiC Ansible Collection Version

dellemc.enterprise.sonic 2.0.0

### SONiC Software Version

4.0.1

### Configuration

CONFIG_FILE() = /home/ansible.cfg
DEFAULT_HOST_LIST(/home/ansible.cfg) = ['/home/inventory/inventory.yml', '/home/inventory/host_cfg_inv_plugin.yaml']
DEFAULT_INVENTORY_PLUGIN_PATH(/home/ansible.cfg) = ['/home/inventory']
DISPLAY_SKIPPED_HOSTS(/home/ansible.cfg) = False
HOST_KEY_CHECKING(/home/ansible.cfg) = False
INJECT_FACTS_AS_VARS(/home/ansible.cfg) = False
INTERPRETER_PYTHON(/home/ansible.cfg) = /usr/bin/python3
PERSISTENT_COMMAND_TIMEOUT(/home/ansible.cfg) = 120
PERSISTENT_CONNECT_TIMEOUT(/home/ansible.cfg) = 120

### Steps to Reproduce

1. Configure  hardware sku - ‘DellEMC-Z9432f-T64C64O8-DPB’ in SONiC device
2. Configure any port to 8x10G or 8x25G
3. Run ansible playbook using sonic_port_breakout module to configure any supported port breakout 

### Expected Behavior

Configures port breakout successfully

### Actual Behavior

Throws below error:
"value of mode must be one of: 1x100G, 1x400G, 1x40G, 2x100G, 2x200G, 2x50G, 4x100G, 4x10G, 4x25G, 4x50G, got: 8x25G found in config"

### Logs

NA

**Comment by kerry-meyer** [comment]
The fix for this problem has been merged into the "main" branch of the enterprise_sonic Ansible collection repo and is available for installation using the instructions posted at "https://github.com/ansible-collections/dellemc.enterprise_sonic/wiki/Installation-of-the-latest-pre-release-version".

It will be included in the 2.3.0 release.
