### ISSUE TITLE
[BUG]: Collection does not support ansible.netcommon 5.x.y, thus latest version will not be included in Ansible 8 until this is fixed

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/dellemc.enterprise_sonic#267]
### Bug Description

Currently the Ansible 8 pre-releases contain dellemc.enterprise_sonic 2.0.0, which claims to support ansible.netcommon 5.x.y. Since ansible.netcommon 5.x.y will be included in Ansible 8, Ansible 8 **cannot** include dellemc.enterprise_sonic 2.1.0 since that release claims to no longer support ansible.netcommon 5.x.y.

Since apparently dellemc.enterprise_sonic 2.0.0 doesn't work with ansible.netcommon 5.x.y - but doesn't document so - Ansible 8 will stick to the broken dellemc.enterprise_sonic 2.0.0 until a later dellemc.enterprise_sonic 2.x.y. release will work with ansible.netcommon 5.x.y again.

Please make sure that your collection is compatible with ansible.netcommon 5.x.y as soon as possible.

Ref: https://github.com/ansible-community/ansible-build-data/issues/233
Ref: #176 which unfortunately does not say what's the problem with ansible.netcommon 5.0.0.

### Product Name

-

### Component or Module Name

-

### DellEMC Enterprise SONiC Ansible Collection Version

2.1.0

### SONiC Software Version

-

### Configuration

-

### Steps to Reproduce

-

### Expected Behavior

-

### Actual Behavior

-

### Logs

-

**Comment by felixfontein** [comment]
If there is a known bad version and you know that the next release will contain a bugfix which will solve the problem, you can also modify the dependency range by excluding that specific version:
```yaml
dependencies: 
  "ansible.netcommon": ">=2.0.0,!=5.0.0"
```
This will avoid installing your collection with `ansible.netcommon` 5.0.0, but will allow installing it with 5.0.1, 5.1.0, etc.

This works with the old collection dependency resolver in ansible-base 2.10 and Ansible 2.9 (https://github.com/ansible/ansible/blob/stable-2.9/lib/ansible/galaxy/collection.py#L212), and also with the new one in ansible-core 2.11+ (https://github.com/ansible/ansible/pull/72678).

**Comment by kerry-meyer** [comment]
Thanks for this information. If we encounter a similar situation in the future, we will handle it this way.

We have completed a 2.2.0 release to address the problem described in this Issue. The 2.2.0 release has been published to Github and to Ansible Galaxy.

We will leave this issue open for a few days to give the submitter time to verify the fixed release.

If everything looks okay, please close this issue.

**Comment by kerry-meyer** [comment]
Thanks for verifying that this fix is compliant.
