### ISSUE TITLE
Collection Requirements Violation - Semantic Versioning

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/dellemc.enterprise_sonic#268]
### Bug Description

According to the changelog (https://github.com/ansible-collections/dellemc.enterprise_sonic/blob/main/CHANGELOG.rst#breaking-changes--porting-guide), the minor 2.1.0 release contains a **breaking change**. This is explicitly prohibited by semantic versioning (https://semver.org/) - breaking changes **must** happen in new major versions.

Semantic versioning is one of the main collection requirements for inclusion in Ansible (https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_requirements.html#versioning-and-deprecation).

In today's Ansible 7.6.0 release, we pinned dellemc.enterprise_sonic to 2.0.0 to avoid breaking changes.

Please undo this breaking change and create a new 2.2.0 minor release without it as soon as possible, or risk freezing dellemc.enterprise_sonic to 2.0.0 for the remainder of the Ansible 7 and 8 release cycles and removal of the collection from Ansible 9.

### Product Name

-

### Component or Module Name

-

### DellEMC Enterprise SONiC Ansible Collection Version

2.1.0

### SONiC Software Version

-

### Configuration

-

### Steps to Reproduce

-

### Expected Behavior

-

### Actual Behavior

-

### Logs

-

**Comment by kerry-meyer** [comment]
Thanks for this notification.

Sorry for the misunderstanding on versioning.

We have a PR submitted to revert the breaking change and will get it merged tomorrow, along with another critical fix (to re-enable installation of Ansible Netcommon versions after 5.0.0) and a version change for our collection to 2.2.0 to encompass these critical fixes.

**Comment by kerry-meyer** [comment]
We have completed a 2.2.0 release to address the problem described in this Issue. The 2.2.0 release has been published to Github and to Ansible Galaxy.

We will leave this issue open for a few days to give the submitter time to verify the fixed release.

If everything looks okay, please close this issue.

**Comment by kerry-meyer** [comment]
Thanks for verifying that this fix is compliant.
