### ISSUE TITLE
[BUG]: Interface naming standard-extended is not supported by the sonic_system module

### ISSUE THREAD

**Issue by MatthewHannonDell** [ansible-collections/dellemc.enterprise_sonic#312]
### Bug Description

When trying to use the sonic_system module with a system that has interface naming standard extended the following error is encountered: "msg": "value of interface_naming must be one of: standard, native, got: standard-ext found in config"

### Product Name

Dell Enterprise SONiC

### Component or Module Name

sonic_system

### DellEMC Enterprise SONiC Ansible Collection Version

dellemc.enterprise_sonic 2.2.0

### SONiC Software Version

4.1.0-Enterprise_Base

### Configuration

N/A (No output)

### Steps to Reproduce

Configure a system with interface-naming standard-extended via the sonic-cli and try to leverage the ansible sonic_system module

### Expected Behavior

Interface naming should support standard, native, and standard-ext

### Actual Behavior

When attempting to change the interface naming state we get the error:
    "msg": "value of interface_naming must be one of: standard, native, got: standard-ext found in config"

### Logs

fatal: [S5212F-1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "config": {
                "anycast_address": null,
                "hostname": "sonic",
                "interface_naming": "standard-ext"
            },
            "state": "merged"
        }
    },
    "msg": "value of interface_naming must be one of: standard, native, got: standard-ext found in config"
}
fatal: [S5212F-2]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "config": {
                "anycast_address": null,
                "hostname": "sonic",
                "interface_naming": "standard-ext"
            },
            "state": "merged"
        }
    },
    "msg": "value of interface_naming must be one of: standard, native, got: standard-ext found in config"
}

**Comment by p3rdu** [comment]
Hi

The same bug seems to apply to dellemc.enterprise_sonic.sonic_l2_interfaces module as well. I'm unable to create configuration and the error mentions standard-ext naming scheme.

```
fatal: [dc-leaf1]: FAILED! => {
    "changed": false,
    "code": 400,
    "invocation": {
        "module_args": {
            "config": [
                {
                    "access": {
                        "vlan": 123
                    },
                    "name": "Eth1/1",
                    "trunk": {
                        "allowed_vlans": [
                            {
                                "vlan": "999"
                            }
                        ]
                    }
                }
            ],
            "state": "merged"
        }
    },
    "msg": "Interface naming mode configured on switch standard-ext, Eth1/1 is not valid"
}
```

**Comment by BrianForget** [comment]
It looks like the options are set in the "ansible_collections.dellemc.enterprise_sonic.plugins.module_utils.network.sonic.argspec.system.system"
That is viewable at https://github.com/ansible-collections/dellemc.enterprise_sonic/blob/main/plugins/modules/sonic_system.py

I suspect that by changing line number 53 standard-extended mode would be accepted.  But my only concern is that the option does require a reboot to take effect.  So perhaps an initial playbook that includes setting the interface-naming mode along with a save and reboot would be needed.

suggested change to line 53:
  from:
       'choices': ['standard', 'native'],
  to:
       'choices': ['standard', 'native', 'standard-ext'],

**Comment by kerry-meyer** [comment]
This issue has been fixed with the merging of:


[Add support for standard_extended interface-naming mode](https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/352)
