### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by MatthewHannonDell** [ansible-collections/dellemc.enterprise_sonic#340]
### Bug Description

sonic_vlans sucessfully creates the vlans but fails to set their description.

### Product Name

Dell Enterprise SONiC

### Component or Module Name

sonic_vlans

### DellEMC Enterprise SONiC Ansible Collection Version

dellemc.enterprise_sonic 2.4.0

### SONiC Software Version

Software Version  : 4.2.0-Enterprise_Base

### Configuration

No output from ansible-config dump --only-changed

### Steps to Reproduce

Leverage sonic_vlans with above versions and following data:
sonic_vlans:
  - vlan_id: 1
    description: 
  - vlan_id: 2
    description: "Servers"
  - vlan_id: 5
    description: "vMotion"
  - vlan_id: 999
    description: "DeadVlan"

### Expected Behavior

VLANs are created along with descriptions

### Actual Behavior

VLANs are created but description is not set. On each subsequent run it reports VLANs as changed but VLAN description is never set.

### Logs

 _____________________
< TASK [Create Vlans] >
 ---------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /mnt/c/Users/Matthew_Hannon/Downloads/ansible_demo_2024_02_20/ansible-sonic-rev1/playbook.yaml:31
redirecting (type: action) dellemc.enterprise_sonic.sonic_vlans to dellemc.enterprise_sonic.sonic
redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
redirecting (type: action) dellemc.enterprise_sonic.sonic_vlans to dellemc.enterprise_sonic.sonic
redirecting (type: action) dellemc.enterprise_sonic.sonic_vlans to dellemc.enterprise_sonic.sonic
redirecting (type: action) dellemc.enterprise_sonic.sonic_vlans to dellemc.enterprise_sonic.sonic
redirecting (type: action) dellemc.enterprise_sonic.sonic_vlans to dellemc.enterprise_sonic.sonic
*** before
--- after
***************
*** 4,18 ****
          'vlan_id': 1
      },
      {
!         'description': null,
          'vlan_id': 2
      },
      {
!         'description': null,
          'vlan_id': 5
      },
      {
!         'description': null,
          'vlan_id': 999
      }
  ]
--- 4,18 ----
          'vlan_id': 1
      },
      {
!         'description': 'Servers',
          'vlan_id': 2
      },
      {
!         'description': 'vMotion',
          'vlan_id': 5
      },
      {
!         'description': 'DeadVlan',
          'vlan_id': 999
      }
  ]
changed: [S5232F-1] => {"after(generated)": [{"description": null, "vlan_id": 1}, {"description": "Servers", "vlan_id": 2}, {"description": "vMotion", "vlan_id": 5}, {"description": "DeadVlan", "vlan_id": 999}], "before": [{"description": null, "vlan_id": 1}, {"description": null, "vlan_id": 2}, {"description": null, "vlan_id": 5}, {"description": null, "vlan_id": 999}], "changed": true, "commands": [{"description": "Servers", "state": "overridden", "vlan_id": 2}, {"description": "vMotion", "state": "overridden", "vlan_id": 5}, {"description": "DeadVlan", "state": "overridden", "vlan_id": 999}]}
*** before
--- after

**Comment by mingjunzhang2019** [comment]
Tested the case with SONIC Rel 4.1, 4.2 and 4.3 (development build) and Ansible Dell collection Rel 2.4 and 2.5 (under development), could not reproduce the issue. The description shows that -C (or --check) option may be used with ansible-playbook. If so, please test again without -C and --check option.

**Comment by MatthewHannonDell** [comment]
I did some additional testing and was able to determine it was an unexpected interaction between sonic_vlans and sonic_interfaces and the workflow in my playbook. In sonic_vlans I was defining a description for the VLANs however in sonic_interfaces that immediately followed I only had the ethernet interfaces. So what was occurring was my playbook was setting the vlan description and then it was being removed by the sonic_interfaces configuration step. While it is a bit strange that the VLAN description is set in each of these resource modules this ultimately was an error in my playbook workflow and this report can be closed.
