### ISSUE TITLE
[QUESTION]: Command Timeout Triggered

### ISSUE THREAD

**Issue by k86td** [ansible-collections/dellemc.enterprise_sonic#349]
### How can the team help?

I'm trying to provision some switches with this Ansible collection.

The switches are from Edgecore and they're running their own Sonic version, so some API endpoints differ a bit. That's why I wanted to try to use `sonic_command` module to run some commands directly on the host.

However, I'm hitting `command timeout triggered`. I've been been following [Ansible guide](https://docs.ansible.com/ansible/latest/network/user_guide/network_debug_troubleshooting.html) to try to debug the issue. I've set the debugging mode and such and I don't seem to find any interesting information.

I was running the following ad-hoc command:
```
ansible -i inventory.ini -m dellemc.enterprise_sonic.sonic_command leaf-sw-875sta-06 -e "ansible_connection=network_cli" -u admin -a "commands=['show version']"
```

## Details
Actual error:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: raise ConnectionError(to_text(msg, errors='surrogate_then_replace'
leaf-sw-875sta-06 | FAILED! => {
    "changed": false,
    "msg": "command timeout triggered, timeout value is 60 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."
}
```

I know that the user can login because I see these in the switch:
```
Jun 19 20:45:50 leaf-sw-875sta-06 sshd[1665270]: Accepted password for admin from <addr> port 34602 ssh2
Jun 19 20:45:50 leaf-sw-875sta-06 sshd[1665270]: pam_unix(sshd:session): session opened for user admin(uid=1000) by (uid=0)
Jun 19 20:45:50 leaf-sw-875sta-06 audit[1665270]: USER_LOGIN pid=1665270 uid=0 auid=1000 ses=304 subj==unconfined msg='op=login id=1000 exe="/usr/sbin/sshd" hostname=<hostname> addr=<addr> terminal=/dev/pts/1 res=success'
Jun 19 20:46:50 leaf-sw-875sta-06 sshd[1665270]: pam_unix(sshd:session): session closed for user admin
```

I've ran with `ANSIBLE_LOG_PATH` and `ANSIBLE_DEBUG=True` with no further useful information. I tried increasing `ANSIBLE_PERSISTENT_COMMAND_TIMEOUT` with no success either.

From the debug log, I can see this:
```
2024-02-29 16:46:28,208 p=975454 u=root n=ansible | network_os is set to dellemc.enterprise_sonic.sonic
2024-02-29 16:46:28,233 p=975464 u=root n=ansible | [DEPRECATION WARNING]: PlayContext.verbosity is deprecated, use
ansible.utils.display.Display.verbosity instead. This feature will be removed
in version 2.18. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
2024-02-29 16:46:28,233 p=975464 u=root n=ansible | [DEPRECATION WARNING]: The connection's stdin object is deprecated. Call
display.prompt_until(msg) instead. This feature will be removed in version
2.19. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
2024-02-29 16:47:28,233 p=975464 u=root n=ansible | command timeout triggered, timeout value is 60 secs.
See the timeout setting options in the Network Debug and Troubleshooting Guide.
2024-02-29 16:47:28,242 p=975454 u=root n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was:     raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
2024-02-29 16:47:28,242 p=975454 u=root n=ansible | leaf-sw-875sta-06 | FAILED! => {
    "changed": false,
    "msg": "command timeout triggered, timeout value is 60 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."
}
2024-02-29 16:47:28,345 p=975464 u=root n=ansible | shutdown complete
```

I'm running with this Ansible version:
```
ansible [core 2.16.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/site-packages/ansible
  ansible collection location = /srv/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.2 (main, Feb 20 2024, 11:40:21) [GCC 8.5.0 20210514 (Red Hat 8.5.0-20)] (/usr/local/bin/python3.10)
  jinja version = 3.1.3
  libyaml = True
```

I'm not too sure what to search for next. I'm not able to pinpoint the error to something specific. Any help would be appreciated,
Thank you

**Comment by kerry-meyer** [comment]
Please append to this issue a copy of the failing playbook, eliding any sensitive/confidential information details. We need to see specifically what operation was being attempted in order to begin analysis on the cause of the timeout.

**Comment by k86td** [comment]
Like I mentionned in the issue, I was testing originally with this AD-HOC command instead of a playbook:
```
ansible -i inventory.ini -m dellemc.enterprise_sonic.sonic_command leaf-sw-875sta-06 -e "ansible_connection=network_cli" -u admin -a "commands=['show version']"
```

**Comment by kerry-meyer** [comment]
Sorry that I didn't notice in your initial description that this was an ad-hoc command. I misread the command as a playbook invocation.

The failing example mixes json and k=v forms for the "-a" argument, resulting in the sending of an invalid command to the device.

The following forms can be used for this ad-hoc command:

```
ansible -i inventory.ini -m dellemc.enterprise_sonic.sonic_command leaf-sw-875sta-06 -c network_cli -a '{"commands": ["show version"]}'
```
and

```
ansible -i tests/regression/hosts -m dellemc.enterprise_sonic.sonic_command leaf-sw-875sta-06 -c network_cli -a "commands='show version'"
```

For the -a content, the first form uses a json string and the second form uses a "k=v" format. (The two forms can not be intermixed as shown in the failing example.) In the first form, multiple commands can be included in the list.) 

Also, the following (valid) portion of the command shown in the failing example:

```
-e "ansible_connection=network_cli"
```

can be replaced with the more compact form:

```
-c network_cli
```

**Comment by kerry-meyer** [comment]
An additional note and request:

Please post the "show version" output from the target switch to show the version of the EdgeCore SONiC OS on which you are attempting to execute this ad-hoc command. (If it is not an "Enterprise SONiC" version, there is no expectation that this collection might work.) Even if it is an "Enterprise SONiC" version, this collection is specifically targeted to Dell's SONiC Enterprise OS and is not guaranteed to work on EdgeCore's OS.

You may want to consider, instead of using the Dell enterprise_sonic resource module collection for this target, using the Ansible Netcommon CLI module: 

[https://docs.ansible.com/ansible/latest/collections/ansible/netcommon/cli_command_module.html#ansible-collections-ansib[…]tcommon-cli-command-module](https://docs.ansible.com/ansible/latest/collections/ansible/netcommon/cli_command_module.html#ansible-collections-ansible-netcommon-cli-command-module)

**Comment by k86td** [comment]
I tested with the JSON ad-hoc command, but it still gives the timeout error. Yeah I understand that the collection wasn't made for Edgecore version, still some things are similar. I wanted to give it a shot.

I'll look into using Netcommon cli
