### ISSUE TITLE
Default MASTER branch should be converted to MAIN branch

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/dellemc.enterprise_sonic#37]
##### SUMMARY
According to the [collection requirements](https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#branch-name-and-configuration),
default branches of the existing repositories under `ansible_collections` SHOULD be converted to use main.

**Comment by javeedf** [comment]
Sorry, we don't have permission to do that. @gundalow can help us on this

![image](https://user-images.githubusercontent.com/11018703/112456752-0e96e600-8d81-11eb-95fc-45a8344fb2b0.png)

**Comment by gundalow** [comment]
@javeedf If you are happy we can make this change.

**Comment by javeedf** [comment]
> @javeedf If you are happy we can make this change.

sure

**Comment by Andersson007** [comment]
@javeedf done, thanks!

**Comment by Andersson007** [comment]
file:///home/aklychko/Pictures/Screenshot%20from%202021-03-26%2011-41-18.png
