### ISSUE TITLE
[FEATURE]: Need support for EVPN Multi-Homing commands in ansible-collection

### ISSUE THREAD

**Issue by avinothcgl** [ansible-collections/dellemc.enterprise_sonic#379]
**Describe the solution you'd like**
 EVPN Multi-Homing commands in ansible-collection. The list of cli falls under Interface PortChannel

**Describe alternatives you've considered**
Currently using network-cli to configure EVPN Multi-Homing commands

`Sonic# show configuration
!
interface PortChannel1
 mtu 9216
 no shutdown
 system-mac 00:00:00:0a:00:01
 !
 evpn ethernet-segment 00:00:00:00:44:38:39:ff:00:01
  df-preference 65503
 !
Sonic(config-if-po1)# evpn
  ethernet-segment  Configure ethernet-segment

Sonic(config-if-po1)# evpn ethernet-segment
  auto-lacp                      Configure ethernet-segment (Type-1)
  auto-system-mac                Configure ethernet-segment (Type-3)
  nn:nn:nn:nn:nn:nn:nn:nn:nn:nn  Ethernet Segment Id (Type-0)

Sonic(config-if-po1)# evpn ethernet-segment 00:00:00:00:44:38:39:ff:00:01
Sonic(config-es-00:00:00:00:44:38:39:ff:00:01)#
  df-preference  Configure DF selection preference
  end            Exit to EXEC mode
  exit           Exit from current mode
  no             Remove settings
`

**Additional context**
[Describe any relevant context or add any relevant screenshots about the feature request.](https://dl.dell.com/content/manual38370705-enterprise-sonic-distribution-by-dell-technologies-user-guide-release-4-2-0.pdf?language=en-us&adobe_mc=MCMID%3D23805331055758533332158801317975096197%7CMCORGID%3D4DD80861515CAB990A490D45%2540AdobeOrg%7CTS%3D1715114419)

**Community Note**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) 
  to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, 
  they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by kerry-meyer** [comment]
With the merging of [Add evpn ethernet-segment support for LAG interface](https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/403), this feature is now available in the enterprise_sonic Ansible resource module collection.
