### ISSUE TITLE
Config src module is not working for dellemc.enterprise_sonic.sonic

### ISSUE THREAD

**Issue by syed-shah100** [ansible-collections/dellemc.enterprise_sonic#47]
I am creating the following config using a template which works on the cli and ansible config `lines` module but when trying to push with config `src` module, it's giving me an error:

config from template:

sonic-1.cfg
```
interface Ethernet0
  ip dhcp-relay 1.1.1.2
interface Ethernet4
  ip dhcp-relay 1.1.1.3
```

config add via cli:
```
sonic-1:~$ sonic-cli
sonic-1# configure terminal
sonic-1(config)# interface Ethernet0
sonic-1(conf-if-Ethernet0)# ip dhcp-relay 1.1.1.2
sonic-1(conf-if-Ethernet0)# end
sonic-1# write memory
sonic-1#
```

config add via ansible task:
```
- name: add config
  dellemc.enterprise_sonic.sonic_config:
    src: ./sonic-1.cfg
    save: yes
```

config error when trying to push with ansible config `src`:
```
TASK [add config] ****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
fatal: [sonic-1]: FAILED! => {"changed": false, "msg": "./sonic-1.cf\u001bEg\r\r\n                     ^\r\n% Error: Invalid input detected at \"^\" marker.\r\n\u0007sonic-1(config)# "}
```

Note: Testing done on the following SONiC code versions

```
SONiC.3.1.0-Cloud_Base
SONiC.3.1.2-Cloud_Base
```

ansible version :
```
ansible==2.10.0
ansible-base==2.10.10
napalm-ansible==0.10.0
```

**Comment by javeedf** [comment]
Its working fine for us. Could you please paste "ansible --version", inventory file output and "ansible-galaxy collection list" command output?

Generally, this happens in older ansible versions. 

refer this https://github.com/ansible-collections/dellemc.enterprise_sonic#setting-environment-variables

run your playbook "ANSIBLE_NETWORK_GROUP_MODULES=sonic ansible-playbook sample_playbook.yaml -i inventory.yaml"

**Comment by syed-shah100** [comment]
@javeedf I have an older ansible version installed in my local user:

ansible --version:
```
ansible 2.9.11
  config file = /home/syed/.ansible.cfg
  configured module search path = ['/home/syed/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/syed/.local/lib/python3.5/site-packages/ansible
  executable location = /home/syed/.local/bin/ansible
  python version = 3.5.2 (default, Jul 17 2020, 14:04:10) [GCC 5.4.0 20160609]
  ```
  
  but I am running my playbook on a virtual machine and there I have a newer version installed:
  
  syed@vm-1:~$ pip freeze | grep ansible
  
  ```
   ansible==2.10.0
ansible-base==2.10.10
napalm-ansible==0.10.0
```

The ansible galaxy command you mentioned does not work:

```
syed@vm-1:~$ ansible-galaxy collection list
usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: 'list' (choose from 'init', 'build', 'publish', 'install')
```

but I have installed the dell sonic module using the following command:

```
ansible-galaxy collection install dellemc.enterprise_sonic
```

and the version installed is `dellemc.enterprise_sonic:1.1.0`

**Comment by javeedf** [comment]
@syed-shah100 is there any success when running as below,

#ANSIBLE_NETWORK_GROUP_MODULES=sonic ansible-playbook sample_playbook.yaml -i inventory.yaml

**Comment by syed-shah100** [comment]
@javeedf I tried with the above command and it still fails.

My inventory:

```
[sonic]
sonic-1

[sonic:vars]
ansible_network_os=dellemc.enterprise_sonic.sonic
ansible_connection=network_cli
```

**Comment by syed-shah100** [comment]
@javeedf After uninstalling and re-installing ansible, my issue got resolved. Thanks for your assistance
